[windows]
172.20.192.1  # Đây là IP mà Ansible đã thấy máy bạn ở lần chạy trước

[windows:vars]
ansible_user=admin
ansible_password="122710"
ansible_connection=winrm
ansible_winrm_server_cert_validation=ignore
ansible_winrm_scheme=http
ansible_port=5985