// <auto-generated />
using System;
using BlazorApp_Manage.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorApp_Manage.Migrations
{
    [DbContext(typeof(WebAppManageContext))]
    [Migration("20260402020251_UpdateSubnetLogic")]
    partial class UpdateSubnetLogic
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlazorApp_Manage.Data.Account", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AccountID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountId"));

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("AccountId")
                        .HasName("PK__Accounts__349DA5864DB56D7F");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "Username" }, "UQ__Accounts__536C85E4EEC4D743")
                        .IsUnique();

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("BlazorApp_Manage.Data.ActionLog", b =>
                {
                    b.Property<long>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("LogID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("LogId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int")
                        .HasColumnName("AccountID");

                    b.Property<string>("ActionType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DeviceId")
                        .HasColumnType("int")
                        .HasColumnName("DeviceID");

                    b.Property<DateTime?>("LogTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("LogId")
                        .HasName("PK__ActionLo__5E5499A84ED10020");

                    b.HasIndex("AccountId");

                    b.HasIndex("DeviceId");

                    b.ToTable("ActionLogs");
                });

            modelBuilder.Entity("BlazorApp_Manage.Data.Device", b =>
                {
                    b.Property<int>("DeviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DeviceID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeviceId"));

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("DeviceTypeId")
                        .HasColumnType("int")
                        .HasColumnName("DeviceTypeID");

                    b.Property<string>("FirmwareVersion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("LocationId")
                        .HasColumnType("int")
                        .HasColumnName("LocationID");

                    b.Property<string>("Macaddress")
                        .HasMaxLength(17)
                        .HasColumnType("nvarchar(17)")
                        .HasColumnName("MACAddress");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Offline");

                    b.HasKey("DeviceId")
                        .HasName("PK__Devices__49E12331B8903405");

                    b.HasIndex("DeviceTypeId");

                    b.HasIndex("LocationId");

                    b.HasIndex(new[] { "SerialNumber" }, "UQ__Devices__048A00086CE5DED3")
                        .IsUnique()
                        .HasFilter("[SerialNumber] IS NOT NULL");

                    b.HasIndex(new[] { "Macaddress" }, "UQ__Devices__95BFB049C362CDEF")
                        .IsUnique()
                        .HasFilter("[MACAddress] IS NOT NULL");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("BlazorApp_Manage.Data.DeviceType", b =>
                {
                    b.Property<int>("TypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TypeID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TypeId"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TypeId")
                        .HasName("PK__DeviceTy__516F039527279123");

                    b.ToTable("DeviceTypes");
                });

            modelBuilder.Entity("BlazorApp_Manage.Data.DeviceVlan", b =>
                {
                    b.Property<int>("DeviceId")
                        .HasColumnType("int")
                        .HasColumnName("DeviceID");

                    b.Property<int>("Vlanid")
                        .HasColumnType("int")
                        .HasColumnName("VLANID");

                    b.Property<DateTime?>("AssignmentDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("DeviceId", "Vlanid")
                        .HasName("PK__DeviceVL__6ED170E987247EE8");

                    b.HasIndex("Vlanid");

                    b.ToTable("DeviceVLANs", (string)null);
                });

            modelBuilder.Entity("BlazorApp_Manage.Data.FirmwareStandard", b =>
                {
                    b.Property<int>("TypeId")
                        .HasColumnType("int")
                        .HasColumnName("TypeID");

                    b.Property<string>("LatestVersion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("datetime");

                    b.HasKey("TypeId")
                        .HasName("PK__Firmware__516F03958B0EF1D6");

                    b.ToTable("FirmwareStandards");
                });

            modelBuilder.Entity("BlazorApp_Manage.Data.Location", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LocationID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocationId"));

                    b.Property<string>("Building")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Floor")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Rack")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Room")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("LocationId")
                        .HasName("PK__Location__E7FEA4776BB8C99F");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("BlazorApp_Manage.Data.NetworkConfig", b =>
                {
                    b.Property<int>("ConfigId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ConfigID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConfigId"));

                    b.Property<string>("DefaultGateway")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<int>("DeviceId")
                        .HasColumnType("int")
                        .HasColumnName("DeviceID");

                    b.Property<string>("Ipaddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("IPAddress");

                    b.Property<string>("PrimaryDns")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("PrimaryDNS");

                    b.Property<string>("SecondaryDns")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("SecondaryDNS");

                    b.Property<string>("SubnetMask")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<DateTime?>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("ConfigId")
                        .HasName("PK__NetworkC__C3BC333C35CC4D54");

                    b.HasIndex(new[] { "DeviceId" }, "UQ__NetworkC__49E123305F253B55")
                        .IsUnique();

                    b.ToTable("NetworkConfigs");
                });

            modelBuilder.Entity("BlazorApp_Manage.Data.Port", b =>
                {
                    b.Property<int>("PortId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PortId"));

                    b.Property<int?>("ConnectedToDeviceId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<string>("PortName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PortNumber")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Vlanid")
                        .HasColumnType("int");

                    b.HasKey("PortId");

                    b.HasIndex("DeviceId");

                    b.HasIndex("Vlanid");

                    b.ToTable("Ports");
                });

            modelBuilder.Entity("BlazorApp_Manage.Data.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleId")
                        .HasName("PK__Roles__8AFACE3AA3AEB444");

                    b.HasIndex(new[] { "RoleName" }, "UQ__Roles__8A2B6160DAEE1EC8")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("BlazorApp_Manage.Data.Vlan", b =>
                {
                    b.Property<int>("Vlanid")
                        .HasColumnType("int")
                        .HasColumnName("VLANID");

                    b.Property<int?>("Cidr")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GatewayIp")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("GatewayIP");

                    b.Property<string>("NetworkAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("SubnetMask")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Vlanname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("VLANName");

                    b.HasKey("Vlanid")
                        .HasName("PK__VLANs__73053D83342B612F");

                    b.ToTable("VLANs", (string)null);
                });

            modelBuilder.Entity("BlazorApp_Manage.Data.Account", b =>
                {
                    b.HasOne("BlazorApp_Manage.Data.Role", "Role")
                        .WithMany("Accounts")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK_Account_Role");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("BlazorApp_Manage.Data.ActionLog", b =>
                {
                    b.HasOne("BlazorApp_Manage.Data.Account", "Account")
                        .WithMany("ActionLogs")
                        .HasForeignKey("AccountId")
                        .IsRequired()
                        .HasConstraintName("FK_Log_Account");

                    b.HasOne("BlazorApp_Manage.Data.Device", "Device")
                        .WithMany("ActionLogs")
                        .HasForeignKey("DeviceId")
                        .HasConstraintName("FK_Log_Device");

                    b.Navigation("Account");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("BlazorApp_Manage.Data.Device", b =>
                {
                    b.HasOne("BlazorApp_Manage.Data.DeviceType", "DeviceType")
                        .WithMany("Devices")
                        .HasForeignKey("DeviceTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_Device_Type");

                    b.HasOne("BlazorApp_Manage.Data.Location", "Location")
                        .WithMany("Devices")
                        .HasForeignKey("LocationId")
                        .HasConstraintName("FK_Device_Location");

                    b.Navigation("DeviceType");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("BlazorApp_Manage.Data.DeviceVlan", b =>
                {
                    b.HasOne("BlazorApp_Manage.Data.Device", "Device")
                        .WithMany("DeviceVlans")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_DV_Device");

                    b.HasOne("BlazorApp_Manage.Data.Vlan", "Vlan")
                        .WithMany("DeviceVlans")
                        .HasForeignKey("Vlanid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_DV_VLAN");

                    b.Navigation("Device");

                    b.Navigation("Vlan");
                });

            modelBuilder.Entity("BlazorApp_Manage.Data.FirmwareStandard", b =>
                {
                    b.HasOne("BlazorApp_Manage.Data.DeviceType", "Type")
                        .WithOne("FirmwareStandard")
                        .HasForeignKey("BlazorApp_Manage.Data.FirmwareStandard", "TypeId")
                        .IsRequired()
                        .HasConstraintName("FK_Std_Type");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("BlazorApp_Manage.Data.NetworkConfig", b =>
                {
                    b.HasOne("BlazorApp_Manage.Data.Device", "Device")
                        .WithOne("NetworkConfig")
                        .HasForeignKey("BlazorApp_Manage.Data.NetworkConfig", "DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Config_Device");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("BlazorApp_Manage.Data.Port", b =>
                {
                    b.HasOne("BlazorApp_Manage.Data.Device", "Device")
                        .WithMany("Ports")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorApp_Manage.Data.Vlan", null)
                        .WithMany("Ports")
                        .HasForeignKey("Vlanid");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("BlazorApp_Manage.Data.Account", b =>
                {
                    b.Navigation("ActionLogs");
                });

            modelBuilder.Entity("BlazorApp_Manage.Data.Device", b =>
                {
                    b.Navigation("ActionLogs");

                    b.Navigation("DeviceVlans");

                    b.Navigation("NetworkConfig");

                    b.Navigation("Ports");
                });

            modelBuilder.Entity("BlazorApp_Manage.Data.DeviceType", b =>
                {
                    b.Navigation("Devices");

                    b.Navigation("FirmwareStandard");
                });

            modelBuilder.Entity("BlazorApp_Manage.Data.Location", b =>
                {
                    b.Navigation("Devices");
                });

            modelBuilder.Entity("BlazorApp_Manage.Data.Role", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("BlazorApp_Manage.Data.Vlan", b =>
                {
                    b.Navigation("DeviceVlans");

                    b.Navigation("Ports");
                });
#pragma warning restore 612, 618
        }
    }
}
